import random
from fastapi import FastAPI
from sqlalchemy.orm import Session
from database import engine, SessionLocal
from models import Tree,Alert,Base

guardians = [
    "Nearby Shop Owner",
    "College Volunteer",
    "Local NGO Member",
    "Resident Welfare Group"
]


app = FastAPI(title="TreeGuard AI Backend")

# Create DB tables
Base.metadata.create_all(bind=engine)

# Home API
@app.get("/")
def home():
    return {"message": "TreeGuard AI Backend Running 🌱"}

# Add Tree API
@app.post("/add-tree")
def add_tree(location: str, age: int):
    db = SessionLocal()
    new_tree = Tree(
        location=location,
        age=age,
        health_status="Healthy",
        lifecycle_stage="Planted",
        guardian="Unassigned"

    )
    db.add(new_tree)
    db.commit()
    db.refresh(new_tree)
    return new_tree

# AI Agent - Update Health
@app.put("/update-health/{tree_id}")
def update_health(tree_id: int, health: str):
    db = SessionLocal()
    tree = db.query(Tree).filter(Tree.id == tree_id).first()

    if not tree:
        db.close()
        return {"error": "Tree not found"}

    tree.health_status = health

    # Health Agent
    if health != "Healthy":
        tree.lifecycle_stage = "At Risk"

    # Guardian Agent
    if tree.lifecycle_stage == "At Risk" and tree.guardian == "Unassigned":
        tree.guardian = random.choice(guardians)

    db.commit()
    db.refresh(tree)
    db.close()

    return {
        "health_agent": "Tree Health Agent",
        "guardian_agent": "Guardian Matching Agent",
        "lifecycle_stage": tree.lifecycle_stage,
        "guardian": tree.guardian
    }

# Alert Agent - Create Alert
@app.post("/alert-agent/{tree_id}")
def alert_agent(tree_id: int):
    db = SessionLocal()
    tree = db.query(Tree).filter(Tree.id == tree_id).first()

    if not tree:
        return {"error": "Tree not found"}

    if tree.lifecycle_stage != "At Risk":
        return {"message": "Tree is healthy. No alert generated."}

    alert = Alert(
        tree_id=tree.id,
        message=f"Tree {tree.id} at {tree.location} requires attention!",
        status="Open"
    )

    db.add(alert)
    db.commit()
    return {"message": "🚨 Alert generated by Alert Agent"}

# View all alerts
@app.get("/alerts")
def get_alerts():
    db = SessionLocal()
    return db.query(Alert).all()


# View all trees
@app.get("/trees")
def get_trees():
    db = SessionLocal()
    return db.query(Tree).all()